"""empty message

Revision ID: 9d8ac46647e0
Revises: 78cf709bcb76
Create Date: 2021-12-09 15:03:48.468499

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "9d8ac46647e0"
down_revision = "78cf709bcb76"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("password", sa.String(length=100), nullable=True),
        sa.Column("name", sa.String(length=1000), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###
