name: Tests
on: [pull_request, push]
jobs:
  linting:
    name: General Linting
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          architecture: x64

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-linting
          restore-keys: ${{ runner.os }}-linting

      - run: pip install bandit black codespell flake8 mypy pyupgrade safety pylint==2.14.4
      - run: pip install types-pytz types-python-dateutil types-redis types-requests types-ujson
      - run: bandit -x ./tests -r . || true
      - run: black --check .
      - run: codespell  --quiet-level=2 --skip=.git,*.csv,*.html,*.ini,*.json,*.lock,*.yaml
      - run: mypy --ignore-missing-imports --exclude="/alembic/" .
      - run: shopt -s globstar && pyupgrade --py36-plus **/*.py
      - run: safety check
      - run: pylint bot main.py
  test:
    name: Base Tests - Ubuntu-latest - Python 3.10
    needs: linting
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          architecture: x64

      - name: Install dependencies
        run: pip install -r requirements-full.txt

      - name: Run tests
        env:
          MPLBACKEND: Agg
        run: |
          pytest tests/
